# Generated by Django 5.1.4 on 2025-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontentclass',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
