# Generated by Django 5.1.4 on 2025-04-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_staticcontentclass_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryclass',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
