# Generated by Django 5.1.4 on 2025-04-06 19:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticcontentclass',
            name='txt',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
